apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    nsg.service: nsg-referenceimplementation
  name: nsg-referenceimplementation
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        nsg.service: nsg-referenceimplementation
    spec:
      containers:
      - env:
        - name: NSG_POSTGRES_DB_URL
          value: {{ required "Missing value NSG_POSTGRES_DB_URL" .Values.NSG_POSTGRES_DB_URL }}
        - name: NSG_POSTGRES_DBO_USER
          value: {{ required "Missing value NSG_POSTGRES_DBO_USER" .Values.NSG_POSTGRES_DBO_USER }}
        - name: NSG_POSTGRES_DBO_PASSWORD
          value: {{ required "Missing value NSG_POSTGRES_DBO_PASSWORD" .Values.NSG_POSTGRES_DBO_PASSWORD }}
        - name: NSG_POSTGRES_USER
          value: {{ required "Missing value NSG_POSTGRES_USER" .Values.NSG_POSTGRES_USER }}
        - name: NSG_POSTGRES_PASSWORD
          value: {{ required "Missing value NSG_POSTGRES_PASSWORD" .Values.NSG_POSTGRES_PASSWORD }}
        name: nsg-referenceimplementation
        image: {{ required "Missing value REFERENCEIMPLEMENTATION_IMAGE" .Values.REFERENCEIMPLEMENTATION_IMAGE }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value NSG_REFERENCEIMPLEMENTATION_MEMORY" .Values.NSG_REFERENCEIMPLEMENTATION_MEMORY | quote }}
      restartPolicy: Always
status: {}
