# Default values for nsg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# API-CAT
NSG_API_CAT_MEMORY: "1400Mi"

# CONCEPT-CAT
NSG_CONCEPT_CAT_MEMORY: "1400Mi"

# INFORMATIONMODEL_CAT
NSG_INFORMATIONMODEL_CAT_MEMORY: "1400Mi"

## Elasticsearch
NSG_ES_CLUSTERNAME: elasticsearch
NSG_ES_CLUSTERNODES: elasticsearch5:9300
NSG_ES_SECURITY: "false"
NSG_ES_MEMORY: "3000Mi"

## FUSEKI
NSG_FUSEKI_MEMORY: "850Mi"

## HARVESTER-API
NSG_HARVESTER_API_MEMORY: "1300Mi"

## HARVESTER
NSG_HARVESTER_MEMORY: "1000Mi"

## NGINX_REGISTRATION
NSG_NGINX_REGISTRATION_MEMORY: "5Mi"

## NGINX_SEARCH
NSG_NGINX_SEARCH_MEMORY: "5Mi"

## REFERENCE_DATA
NSG_REFERENCE_DATA_MEMORY: "900Mi"

## REGISTRATION_API
NSG_REGISTRATION_API_MEMORY: "1500Mi"

## REGISTRATION_AUTH
NSG_REGISTRATION_AUTH_MEMORY: "600Mi"

## REGISTRATION_REACT
NSG_REGISTRATION_REACT_MEMORY: "1000Mi"

## SEARCH_API
NSG_SEARCH_API_MEMORY: "1500Mi"

## SEARCH
NSG_SEARCH_MEMORY: "100Mi"
